### ISSUE TITLE
Buffersize in Solid.Arduino.ArduinoSession too small for Mega 2560

### ISSUE THREAD

**Issue by dkurok** [SolidSoils/Arduino#10]
Hello, I tried your samplecode and during the call of firmata.GetBoardCapability(); I get an OverflowException thrown by WriteMessageByte(int dataByte).
When I change the BufferSize from 512 to 2048 (I went deeper to get somehow narrow it down; for my board, an original Arduino Mega 2560, which has 70 ports to report,  the responses-message for GetBoardCapability is 547 Bytes long) in ArduinoSession, the call works. At the Moment I don't want to pull something into Git, because I do my dev on VS 2013 and I'm not sure whether I can without any sideeffects...
So maybe it'S better for someone of the contributors
Regards

Dietmar
@dkurok

**Comment by SolidSoils** [comment]
Thank you for your contribution.

I increased the buffer size to 2048 and committed the change to the main branch.

Henk
