### ISSUE TITLE
System.IO.IOException running example

### ISSUE THREAD

**Issue by ignitec** [SolidSoils/Arduino#15]
> System.IO.IOException occurred
>   HResult=0x80070057
>   Message=The parameter is incorrect.
> 
>   Source=System
>   StackTrace:
>    at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
>    at System.IO.Ports.InternalResources.WinIOError()
>    at System.IO.Ports.SerialStream.InitializeDCB(Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Boolean discardNull)
>    at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
>    at System.IO.Ports.SerialPort.Open()
>    at Solid.Arduino.EnhancedSerialPort.Open() in Arduino-master\Solid.Arduino\EnhancedSerialPort.cs:line 108
>    at Solid.Arduino.ArduinoSession..ctor(ISerialConnection connection) in Arduino-master\Solid.Arduino\ArduinoSession.cs:line 157
>    at Solid.Arduino.ArduinoSession..ctor(ISerialConnection connection, Int32 timeOut) in Arduino-master\Solid.Arduino\ArduinoSession.cs:line 170
>    at Solid.Arduino.SerialConnection.FindConnection(Func`2 isDeviceAvailable, String[] portNames, SerialBaudRate[] baudRates) in Arduino-master\Solid.Arduino\SerialConnection.cs:line 236
>    at Solid.Arduino.SerialConnection.FindSerialConnection() in Arduino-master\Solid.Arduino\SerialConnection.cs:line 148
>    at Solid.Arduino.Run.Program.AutoOpenTest() in Arduino-master\Solid.Arduino.Run\Program.cs:line 29
>    at Solid.Arduino.Run.Program.Main(String[] args) in Arduino-master\Solid.Arduino.Run\Program.cs:line 19
> 

I'm using Visual Studio 2017 (15.2)
Using an Arduino Due on programming port (COM5).  

I've changed all 'COM3' strings to 'COM5'. 

I am trying to run the project "Solid.Arduino.Run". I compiled and uploaded StandardFirmata.ino from https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino

base.Open(); seems to throw the above Exception.

**Comment by SolidSoils** [comment]
According to the stacktrace the exception occurs at the following line:

    return connection ?? FindConnection(isAvailableFunc, portNames, OtherBaudRates);

Here `FindConnection` tries to find the Arduino board using less common baud rates, i.e.

        private static readonly SerialBaudRate[] OtherBaudRates =
        {
            SerialBaudRate.Bps_28800,
            SerialBaudRate.Bps_14400,
            SerialBaudRate.Bps_38400,
            SerialBaudRate.Bps_31250,
            SerialBaudRate.Bps_4800,
            SerialBaudRate.Bps_2400
        };

Perhaps one of these baud rates is not supported on your computer. On what OS is Visual Studio running and what's the baud rate your board is operating on?
