### ISSUE TITLE
How to handle multiple Arduino boards

### ISSUE THREAD

**Issue by WaldoPepper** [SolidSoils/Arduino#20]
Hi,

I am working on a quite complex setup with (at least) three Arduino UNO I would like to control them from one PC using FirmataStandard.

Each Arduino has a distinct function in the setup and has to be identified correctly on startup (assigned COM ports may vary between startups).

I can rename the FirmataStandard sketch to something unique and I think I can identify the board by using GetFirmware() and query firmware.Name.

But what is the best approach in general to discover more than one Arduino at startup?

Thanks

Kai

**Comment by SolidSoils** [comment]
I do not have a best approach, but a possible solution would be to install the follow sketch on your Arduino boards:

```
#include <Firmata.h>

char query[] = "Identify";
char reply[] = "ArduinoA";

void setup()
{
  Serial.begin(9600);
  while (!Serial) {}
}

void loop()
{
  if (Serial.find(query))
  {
    Serial.println(reply);
  }
  else
  {
    Serial.println("Listening...");
    Serial.flush();
  }
  
  delay(25);
}
```

Then you can find the board named "ArduinoA" like this:

```csharp
using (var arduinoConnection = SerialConnection.Find("Identify", "ArduinoA"))
    Assert.IsNotNull(arduinoConnection);
```
