### ISSUE TITLE
Initialize Connection To Specific COM Port

### ISSUE THREAD

**Issue by nickdaria** [SolidSoils/Arduino#28]
I know it's a little far fetched since there hasn't been much activity here, but is there any way to connect directly to a specific COM Port and/or baud rate without searching? I have been trying everything I could with the docs, and the query method won't work for me.

**Comment by SolidSoils** [comment]
Just use the constructor of the SerialConnection or the EnhancedSerialConnection class. It's documented [here](https://solidsoils.github.io/Arduino/html/acc5321a-11b6-194d-9978-a32b2a7ec2a3.htm).
