### ISSUE TITLE
EnhancedSerialConnection.Find() does not find the connected Arduino Nano Every.

### ISSUE THREAD

**Issue by jaak0b** [SolidSoils/Arduino#42]
I tried the basic test from the starting page, even though an Arduino nano every was connected, the library could not detect the Arduino Nano Every. The Arduino can be seen by the Arduino IDE and System.IO.Ports.SerialPort. 

![image](https://user-images.githubusercontent.com/53713395/147842636-668ae0ba-b48a-4489-8578-7b7f268e0345.png)

Please note, that the com port was not blocked by the Arduino IDE because the board was not selected.

**Comment by SolidSoils** [comment]
When it cannot find the connection automatically, try specifying the COM-port and baudrate manually.
